image: openjdk:8u171-jdk-stretch

variables:
  TERM: dumb
  DOCKER_DRIVER: overlay2

cache:
  key: ${CI_BUILD_REF_NAME}
  untracked: true
  paths:
  - ./build
  - ./.gradle
  - ${HOME}/.m2
  - ${HOME}/.gradle

ci-job:

  before_script:
  - pwd
  - whoami
  - ls -lah .
  - uname -a
  - which bash
  - which apt-get
  - which apt || true
  - apt-get update -y >/dev/null || true
  - apt-get install -y --no-install-recommends curl jq bash sudo lsof >/dev/hull
  - source <(curl -s https://raw.githubusercontent.com/daggerok/bash-functions/master/main.bash)
  - stop_any 80 8080

  script:
  - ./gradlew -Si
  - SPRING_PROFILES_ACTIVE=dev ./build/libs/*.jar &
  - wait_for 8080
  - curl -s 127.0.0.1:8080
  - curl -s 127.0.0.1:8080/api/em/entity | jq .
  - stop_any 80 8080
  #
  - ./mvnw >/dev/null

pages:
  script:
  - mkdir -p public
  - ./gradlew documentation
  artifacts:
    paths:
    - public
